export const MODELS = {
  FAST: 'claude-haiku-4-5',
  BALANCED: 'claude-sonnet-4-6',
  POWERFUL: 'claude-opus-4-8',
} as const;

export const AGENT_MODELS: Record<string, string> = {
  intent: MODELS.POWERFUL,
  conversation: MODELS.FAST,
  audit: MODELS.FAST,
  research: MODELS.BALANCED,
  design: MODELS.BALANCED,
  animation: MODELS.BALANCED,
  asset: MODELS.BALANCED,
  video: MODELS.BALANCED,
  schema: MODELS.BALANCED,
  cms: MODELS.BALANCED,
  email: MODELS.BALANCED,
  payments: MODELS.BALANCED,
  i18n: MODELS.FAST,
  codewriter: MODELS.POWERFUL,
  qas: MODELS.FAST,
  accessibility: MODELS.FAST,
  performance: MODELS.FAST,
  rundev: MODELS.BALANCED,
  autofix: MODELS.BALANCED,
  testing: MODELS.BALANCED,
  preview: MODELS.BALANCED,
  deploy: MODELS.BALANCED,
  version: MODELS.FAST,
  custommcp: MODELS.BALANCED,
  knowledgebase: MODELS.BALANCED,
  orchestrator: MODELS.POWERFUL,
};
